"""init_schema

Revision ID: d77b2abbac8d
Revises: 
Create Date: 2026-03-06 14:23:05.850266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd77b2abbac8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('rate_limit_hour', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('batch_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cv_count', sa.Integer(), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('total_cost_usd', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('total_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_name', sa.String(length=255), nullable=True),
    sa.Column('overall_aqs', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('research_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('education_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('teaching_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('fitment_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('recommendation', sa.String(length=50), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('job_description_hash', sa.String(length=64), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('api_key_hash', sa.String(length=64), nullable=True),
    sa.Column('cost_usd', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyses')
    op.drop_table('batch_jobs')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
